#pragma once
#include <windef.h>

#define D3D10_ENTRY_COUNT(Class) (D3D10_##Class##_LastEntry - D3D10_##Class##_FirstEntry + 1)

enum
{
	D3D10_SwapChain_FirstEntry,
	D3D10_SwapChain_QueryInterface = D3D10_SwapChain_FirstEntry,
	D3D10_SwapChain_AddRef,
	D3D10_SwapChain_Release,
	D3D10_SwapChain_SetPrivateData,
	D3D10_SwapChain_SetPrivateDataInterface,
	D3D10_SwapChain_GetPrivateData,
	D3D10_SwapChain_GetParent,
	D3D10_SwapChain_GetDevice,
	D3D10_SwapChain_Present,
	D3D10_SwapChain_GetBuffer,
	D3D10_SwapChain_SetFullscreenState,
	D3D10_SwapChain_GetFullscreenState,
	D3D10_SwapChain_GetDesc,
	D3D10_SwapChain_ResizeBuffers,
	D3D10_SwapChain_ResizeTarget,
	D3D10_SwapChain_GetContainingOutput,
	D3D10_SwapChain_GetFrameStatistics,
	D3D10_SwapChain_GetLastPresentCount,
	D3D10_SwapChain_LastEntry = D3D10_SwapChain_GetLastPresentCount,

	D3D10_Device_FirstEntry,
	D3D10_Device_QueryInterface = D3D10_Device_FirstEntry,
	D3D10_Device_AddRef,
	D3D10_Device_Release,
	D3D10_Device_VSSetConstantBuffers,
	D3D10_Device_PSSetShaderResources,
	D3D10_Device_PSSetShader,
	D3D10_Device_PSSetSamplers,
	D3D10_Device_VSSetShader,
	D3D10_Device_DrawIndexed,
	D3D10_Device_Draw,
	D3D10_Device_PSSetConstantBuffers,
	D3D10_Device_IASetInputLayout,
	D3D10_Device_IASetVertexBuffers,
	D3D10_Device_IASetIndexBuffer,
	D3D10_Device_DrawIndexedInstanced,
	D3D10_Device_DrawInstanced,
	D3D10_Device_GSSetConstantBuffers,
	D3D10_Device_GSSetShader,
	D3D10_Device_IASetPrimitiveTopology,
	D3D10_Device_VSSetShaderResources,
	D3D10_Device_VSSetSamplers,
	D3D10_Device_SetPredication,
	D3D10_Device_GSSetShaderResources,
	D3D10_Device_GSSetSamplers,
	D3D10_Device_OMSetRenderTargets,
	D3D10_Device_OMSetBlendState,
	D3D10_Device_OMSetDepthStencilState,
	D3D10_Device_SOSetTargets,
	D3D10_Device_DrawAuto,
	D3D10_Device_RSSetState,
	D3D10_Device_RSSetViewports,
	D3D10_Device_RSSetScissorRects,
	D3D10_Device_CopySubresourceRegion,
	D3D10_Device_CopyResource,
	D3D10_Device_UpdateSubresource,
	D3D10_Device_ClearRenderTargetView,
	D3D10_Device_ClearDepthStencilView,
	D3D10_Device_GenerateMips,
	D3D10_Device_ResolveSubresource,
	D3D10_Device_VSGetConstantBuffers,
	D3D10_Device_PSGetShaderResources,
	D3D10_Device_PSGetShader,
	D3D10_Device_PSGetSamplers,
	D3D10_Device_VSGetShader,
	D3D10_Device_PSGetConstantBuffers,
	D3D10_Device_IAGetInputLayout,
	D3D10_Device_IAGetVertexBuffers,
	D3D10_Device_IAGetIndexBuffer,
	D3D10_Device_GSGetConstantBuffers,
	D3D10_Device_GSGetShader,
	D3D10_Device_IAGetPrimitiveTopology,
	D3D10_Device_VSGetShaderResources,
	D3D10_Device_VSGetSamplers,
	D3D10_Device_GetPredication,
	D3D10_Device_GSGetShaderResources,
	D3D10_Device_GSGetSamplers,
	D3D10_Device_OMGetRenderTargets,
	D3D10_Device_OMGetBlendState,
	D3D10_Device_OMGetDepthStencilState,
	D3D10_Device_SOGetTargets,
	D3D10_Device_RSGetState,
	D3D10_Device_RSGetViewports,
	D3D10_Device_RSGetScissorRects,
	D3D10_Device_GetDeviceRemovedReason,
	D3D10_Device_SetExceptionMode,
	D3D10_Device_GetExceptionMode,
	D3D10_Device_GetPrivateData,
	D3D10_Device_SetPrivateData,
	D3D10_Device_SetPrivateDataInterface,
	D3D10_Device_ClearState,
	D3D10_Device_Flush,
	D3D10_Device_CreateBuffer,
	D3D10_Device_CreateTexture1D,
	D3D10_Device_CreateTexture2D,
	D3D10_Device_CreateTexture3D,
	D3D10_Device_CreateShaderResourceView,
	D3D10_Device_CreateRenderTargetView,
	D3D10_Device_CreateDepthStencilView,
	D3D10_Device_CreateInputLayout,
	D3D10_Device_CreateVertexShader,
	D3D10_Device_CreateGeometryShader,
	D3D10_Device_CreateGeometryShaderWithStreamOutput,
	D3D10_Device_CreatePixelShader,
	D3D10_Device_CreateBlendState,
	D3D10_Device_CreateDepthStencilState,
	D3D10_Device_CreateRasterizerState,
	D3D10_Device_CreateSamplerState,
	D3D10_Device_CreateQuery,
	D3D10_Device_CreatePredicate,
	D3D10_Device_CreateCounter,
	D3D10_Device_CheckFormatSupport,
	D3D10_Device_CheckMultisampleQualityLevels,
	D3D10_Device_CheckCounterInfo,
	D3D10_Device_CheckCounter,
	D3D10_Device_GetCreationFlags,
	D3D10_Device_OpenSharedResource,
	D3D10_Device_SetTextFilterSize,
	D3D10_Device_GetTextFilterSize,
	D3D10_Device_LastEntry = D3D10_Device_GetTextFilterSize,
};

static const UINT D3D10_SWAPCHAIN_ENTRIES = D3D10_ENTRY_COUNT(SwapChain);
static const UINT D3D10_DEVICE_ENTRIES = D3D10_ENTRY_COUNT(Device);
