#pragma once
#include <windef.h>

#define DDRAW_ENTRY_COUNT(Class) (DDRAW_##Class##_LastEntry - DDRAW_##Class##_FirstEntry + 1)


enum
{
	DDRAW_Device_FirstEntry,
	DDRAW_Device_QueryInterface = DDRAW_Device_FirstEntry,
	DDRAW_Device_AddRef,
	DDRAW_Device_Release,
	DDRAW_Device_Compact,
	DDRAW_Device_CreateClipper,
	DDRAW_Device_CreatePalette,
	DDRAW_Device_CreateSurface,
	DDRAW_Device_DuplicateSurface,
	DDRAW_Device_EnumDisplayModes,
	DDRAW_Device_EnumSurfaces,
	DDRAW_Device_FlipToGDISurface,
	DDRAW_Device_GetCaps,
	DDRAW_Device_GetDisplayMode,
	DDRAW_Device_GetFourCCCodes,
	DDRAW_Device_GetGDISurface,
	DDRAW_Device_GetMonitorFrequency,
	DDRAW_Device_GetScanLine,
	DDRAW_Device_GetVerticalBlankStatus,
	DDRAW_Device_Initialize,
	DDRAW_Device_RestoreDisplayMode,
	DDRAW_Device_SetCooperativeLevel,
	DDRAW_Device_SetDisplayMode,
	DDRAW_Device_WaitForVerticalBlank,
	DDRAW_Device_GetAvailableVidMem,
	DDRAW_Device_GetSurfaceFromDC,
	DDRAW_Device_RestoreAllSurfaces,
	DDRAW_Device_TestCooperativeLevel,
	DDRAW_Device_GetDeviceIdentifier,
	DDRAW_Device_StartModeTest,
	DDRAW_Device_EvaluateMode,
	DDRAW_Device_LastEntry = DDRAW_Device_EvaluateMode,

	DDRAW_Surface_FirstEntry,
	DDRAW_Surface_QueryInterface = DDRAW_Surface_FirstEntry,
	DDRAW_Surface_AddRef,
	DDRAW_Surface_Release,
	DDRAW_Surface_AddAttachedSurface,
	DDRAW_Surface_AddOverlayDirtyRect,
	DDRAW_Surface_Blt,
	DDRAW_Surface_BltBatch,
	DDRAW_Surface_BltFast,
	DDRAW_Surface_DeleteAttachedSurface,
	DDRAW_Surface_EnumAttachedSurfaces,
	DDRAW_Surface_EnumOverlayZOrders,
	DDRAW_Surface_Flip,
	DDRAW_Surface_GetAttachedSurface,
	DDRAW_Surface_GetBltStatus,
	DDRAW_Surface_GetCaps,
	DDRAW_Surface_GetClipper,
	DDRAW_Surface_GetColorKey,
	DDRAW_Surface_GetDC,
	DDRAW_Surface_GetFlipStatus,
	DDRAW_Surface_GetOverlayPosition,
	DDRAW_Surface_GetPalette,
	DDRAW_Surface_GetPixelFormat,
	DDRAW_Surface_GetSurfaceDesc,
	DDRAW_Surface_Initialize,
	DDRAW_Surface_IsLost,
	DDRAW_Surface_Lock,
	DDRAW_Surface_ReleaseDC,
	DDRAW_Surface_Restore,
	DDRAW_Surface_SetClipper,
	DDRAW_Surface_SetColorKey,
	DDRAW_Surface_SetOverlayPosition,
	DDRAW_Surface_SetPalette,
	DDRAW_Surface_Unlock,
	DDRAW_Surface_UpdateOverlay,
	DDRAW_Surface_UpdateOverlayDisplay,
	DDRAW_Surface_UpdateOverlayZOrder,
	DDRAW_Surface_GetDDInterface,
	DDRAW_Surface_PageLock,
	DDRAW_Surface_PageUnlock,
	DDRAW_Surface_SetSurfaceDesc,
	DDRAW_Surface_SetPrivateData,
	DDRAW_Surface_GetPrivateData,
	DDRAW_Surface_FreePrivateData,
	DDRAW_Surface_GetUniquenessValue,
	DDRAW_Surface_ChangeUniquenessValue,
	DDRAW_Surface_SetPriority,
	DDRAW_Surface_GetPriority,
	DDRAW_Surface_SetLOD,
	DDRAW_Surface_GetLOD,
	DDRAW_Surface_LastEntry = DDRAW_Surface_GetLOD,

	DDRAW_Clipper_FirstEntry,
	DDRAW_Clipper_QueryInterface = DDRAW_Clipper_FirstEntry,
	DDRAW_Clipper_AddRef,
	DDRAW_Clipper_Release,
	DDRAW_Clipper_GetClipList,
	DDRAW_Clipper_GetHWnd,
	DDRAW_Clipper_Initialize,
	DDRAW_Clipper_IsClipListChanged,
	DDRAW_Clipper_SetClipList,
	DDRAW_Clipper_SetHWnd,
	DDRAW_Clipper_LastEntry = DDRAW_Clipper_SetHWnd
};

static const UINT DDRAW_DEVICE_ENTRIES = DDRAW_ENTRY_COUNT(Device);
static const UINT DDRAW_SURFACE_ENTRIES = DDRAW_ENTRY_COUNT(Surface);
static const UINT DDRAW_CLIPPER_ENTRIES = DDRAW_ENTRY_COUNT(Clipper);
