#pragma once

#define ENTRY_COUNT(Class) (Class##_LastEntry - Class##_FirstEntry + 1)


namespace directhook::ddraw
{
	enum
	{
		Device_FirstEntry,
		Device_QueryInterface = Device_FirstEntry,
		Device_AddRef,
		Device_Release,
		Device_Compact,
		Device_CreateClipper,
		Device_CreatePalette,
		Device_CreateSurface,
		Device_DuplicateSurface,
		Device_EnumDisplayModes,
		Device_EnumSurfaces,
		Device_FlipToGDISurface,
		Device_GetCaps,
		Device_GetDisplayMode,
		Device_GetFourCCCodes,
		Device_GetGDISurface,
		Device_GetMonitorFrequency,
		Device_GetScanLine,
		Device_GetVerticalBlankStatus,
		Device_Initialize,
		Device_RestoreDisplayMode,
		Device_SetCooperativeLevel,
		Device_SetDisplayMode,
		Device_WaitForVerticalBlank,
		Device_GetAvailableVidMem,
		Device_GetSurfaceFromDC,
		Device_RestoreAllSurfaces,
		Device_TestCooperativeLevel,
		Device_GetDeviceIdentifier,
		Device_StartModeTest,
		Device_EvaluateMode,
		Device_LastEntry = Device_EvaluateMode,

		Surface_FirstEntry,
		Surface_QueryInterface = Surface_FirstEntry,
		Surface_AddRef,
		Surface_Release,
		Surface_AddAttachedSurface,
		Surface_AddOverlayDirtyRect,
		Surface_Blt,
		Surface_BltBatch,
		Surface_BltFast,
		Surface_DeleteAttachedSurface,
		Surface_EnumAttachedSurfaces,
		Surface_EnumOverlayZOrders,
		Surface_Flip,
		Surface_GetAttachedSurface,
		Surface_GetBltStatus,
		Surface_GetCaps,
		Surface_GetClipper,
		Surface_GetColorKey,
		Surface_GetDC,
		Surface_GetFlipStatus,
		Surface_GetOverlayPosition,
		Surface_GetPalette,
		Surface_GetPixelFormat,
		Surface_GetSurfaceDesc,
		Surface_Initialize,
		Surface_IsLost,
		Surface_Lock,
		Surface_ReleaseDC,
		Surface_Restore,
		Surface_SetClipper,
		Surface_SetColorKey,
		Surface_SetOverlayPosition,
		Surface_SetPalette,
		Surface_UpdateOverlay,
		Surface_UpdateOverlayDisplay,
		Surface_UpdateOverlayZOrder,
		Surface_GetDDInterface,
		Surface_PageLock,
		Surface_PageUnlock,
		Surface_SetSurfaceDesc,
		Surface_SetPrivateData,
		Surface_GetPrivateData,
		Surface_FreePrivateData,
		Surface_GetUniquenessValue,
		Surface_ChangeUniquenessValue,
		Surface_SetPriority,
		Surface_GetPriority,
		Surface_SetLOD,
		Surface_GetLOD,
		Surface_LastEntry = Surface_GetLOD,

		Clipper_FirstEntry,
		Clipper_QueryInterface = Clipper_FirstEntry,
		Clipper_AddRef,
		Clipper_Release,
		Clipper_GetClipList,
		Clipper_GetHWnd,
		Clipper_Initialize,
		Clipper_IsClipListChanged,
		Clipper_SetClipList,
		Clipper_SetHWnd,
		Clipper_LastEntry = Clipper_SetHWnd
	};

	static constexpr int DEVICE_ENTRIES = ENTRY_COUNT(Device);
	static constexpr int SURFACE_ENTRIES = ENTRY_COUNT(Surface);
	static constexpr int CLIPPER_ENTRIES = ENTRY_COUNT(Clipper);
}
